### ISSUE TITLE
Can only jail Police or other Admins

### ISSUE THREAD

**Issue by tr1age** [TehRamsus/esx_extendedjail#10]
I’ve run into an issue due to these lines:

```
ESX.RegisterCommand('jail', 'admin', function(xPlayer, args, showError)
	JailPlayer(args.playerId, args.time, { jail = 'prison', type = 'first', time = args.time}, xPlayer)
end, true, {help = 'Jail Player', validate = true, arguments = {
	{name = 'playerId', help = 'Player ID', type = 'playerId'},
	{name = 'time', help = 'Minutes', type = 'number'}
}})
```
Only an admin can jail another admin. You cannot jail other players. Only admins. if you set admint o police you can only jail police as a police. How do I make it so a police can jail anyone?

**Comment by vanemp21** [comment]
same issue for me, I tried to changing 'admin' by 'user' and nothing happens. Only admins or polices can be jailed

**Comment by tr1age** [comment]
> same issue for me, I tried to changing 'admin' by 'user' and nothing happens. Only admins or polices can be jailed

Yeah I tried that as well no go. Not sure where the call is even coming from looking over all the code.

**Comment by TehRamsus** [comment]
Hey there. This issue is now fixed. Please update latest version of extendedjail script. If you got any new errors, please open issue. 
**Issue is now closed**
