### ISSUE TITLE
New update "/jail" doesn't teleport to jail

### ISSUE THREAD

**Issue by tr1age** [TehRamsus/esx_extendedjail#11]
Resolved with this code:

Take out lines
`	else
		(ESX.GetPlayerFromId(source.playerId)).triggerEvent('chatMessage', "[ JAIL ]" , {255, 255, 255}, _U('no_permissions'))
		if Config.IsWebhookEnabled then Webhook("2061822", _U('alert'), _U('tried_without_permission', GetPlayerName(playerId), xPlayerTarget.getIdentifier())) end
	end`

and 
`	if xPlayerTarget.job.name == Config.Job or xPlayerTarget.getGroup() == Config.AdminTitle then`

of server/main.lua

**Comment by TehRamsus** [comment]
Hey. Oh, true. This will be fixed soon!
