### ISSUE TITLE
Error..

### ISSUE THREAD

**Issue by Apo1337** [TehRamsus/esx_extendedjail#12]
I get many times this error in console. I dont know why. How to fix that?

https://www.bilder-upload.eu/upload/00a320-1621955885.png

**Comment by TehRamsus** [comment]
Okey then, what is you current esx version? As I said in docs and forum, we do not offer support to oldest esx, only 1.2. If you have 1.2, can you explain, what happen before error appears?

**Comment by Apo1337** [comment]
Cant reproduce it.. Just happen randomly
