### ISSUE TITLE
Passing webhook url to client

### ISSUE THREAD

**Issue by Poggicek** [TehRamsus/esx_extendedjail#16]
The config is passed both to the client and the server. Anyone can easily dump the client and abuse the webhook

https://github.com/TehRamsus/esx_extendedjail/blob/5c32bf418f57d6e6d40777c5a53e5ddb5918ee25/config.lua#L31

**Comment by TehRamsus** [comment]
Then you have to fix it, it is not my fault 😂

**Comment by Poggicek** [comment]
How is it not your fault when you literally made the resource

**Comment by TehRamsus** [comment]
Why you are here if you don't know how to fix it? I don't give any respect for people who literally copy&paste scripts without looking the code...

**Comment by TehRamsus** [comment]
> # THIS PROJECT HAS BEEN DISCONTINUED
